spring:
  sql:
    init:
      platform: h2
  datasource:
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
logging:
  level:
    com:
      photography:
        demo: TRACE
    org:
      hibernate:
        SQL: TRACE
        type.descriptor.sql.BasicBinder: TRACE
      springframework:
        cache: TRACE
